[build]
base = "/"
command = "yarn build"
publish = "build"

[[redirects]]
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"

[[redirects]]
from = "/*"
to = "/art/:splat"

[functions]
directory = "functions/"
