[build]
base = "/"
command = "yarn export"
publish = "__sapper__/export"

[[redirects]]
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"

[[redirects]]
from = "/*"
to = "/art/:splat"

[functions]
directory = "functions/"
